import { newId } from './lib/id';
import { useState, useEffect, useRef } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { LayoutDashboard, GitBranch, MessageSquare, BarChart3, TrendingUp, ShieldCheck, ChevronDown, ChevronRight, ArrowUpRight, ArrowRight, Plus, Search, SlidersHorizontal, Clock3, CircleCheck, AlertTriangle, Zap, X, Check, LockKeyhole, RefreshCw, Info, Activity, Send, UserRound, Stethoscope, Pill, Bell, Download, LogOut, CheckCircle2, Copy, FlaskConical, ExternalLink } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import Circuit, { Signal } from './components/Circuit';
import WaitingTimer from './components/WaitingTimer';
import Copilot from './components/Copilot';
import { useNow } from './lib/useNow';
import { INPUTS, signal, state, nextAction, permitted, patientText, comparator, roleNames, gateOpen, needsAttention, waitingExplanation } from './domain/engine';
import type { ActionType, RefillCase, Role, InputKey } from './domain/engine';
import { seedCases, SCENARIOS } from './domain/seed';
import { connected, supabase, api, loadDemo, saveDemo, demoAction, demoCreate } from './lib/data';
import { Growth, Insights, System } from './views';
type Page='workspace'|'lab'|'updates'|'insights'|'growth'|'system';
const pages:{id:Page;label:string;icon:LucideIcon}[]=[{id:'workspace',label:'Refill workspace',icon:LayoutDashboard},{id:'lab',label:'Circuit lab',icon:GitBranch},{id:'updates',label:'Patient updates',icon:MessageSquare},{id:'insights',label:'Insights',icon:BarChart3},{id:'growth',label:'Growth playbook',icon:TrendingUp},{id:'system',label:'System & trust',icon:ShieldCheck}];
const roleIcons:Record<Role,LucideIcon>={staff:UserRound,clinician:Stethoscope,pharmacy:Pill};
export const humanTime=(value:string)=>new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
export const ageHours=(c:RefillCase)=>Math.max(0,Math.floor((Date.now()-new Date(c.createdAt).getTime())/3600000));
export const isClosed=(c:RefillCase)=>c.transport==='dispensed'||c.declined;
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>;}
export function statusTone(c:RefillCase){const s=state(c);return s==='Resolved'?'green':c.hold||c.transport==='failed'?'red':s==='Ready to route'||s==='Ready for pickup'?'green':'amber';}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const d=ref.current;d?.showModal();return()=>d?.close();},[]);
 return <dialog ref={ref} className="modal" onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-title"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={20}/></button></div>{children}</dialog>;
}
function Login(){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);setError('');const form=new FormData(e.currentTarget);const {error}=await supabase.auth.signInWithPassword({email:String(form.get('email')),password:String(form.get('password'))});setBusy(false);if(error)setError(error.message);}
 return <div className="login-screen"><div className="login-card"><div className="brand"><span className="brand-mark">r</span><b>RelayRx<span>™</span></b></div><Badge tone="amber">Connected sandbox · synthetic data only</Badge><h1>Your refill workspace.</h1><p>Sign in with an account provisioned for your practice.</p>{!supabase?<p className="error-box">Supabase configuration is missing. Follow the connected sandbox steps in README.md, or use VITE_DATA_MODE=demo.</p>:<form onSubmit={login}><label>Email<input name="email" type="email" required autoComplete="username"/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label>{error&&<p className="error-box" role="alert">{error}</p>}<button className="button primary" disabled={busy}>{busy?'Signing in…':'Sign in'}<ArrowRight size={17}/></button></form>}<small>Clinical and pharmacy integrations are simulated.</small></div></div>;
}
export default function App(){
 const fromPath=()=>pages.find(p=>`/${p.id}`===location.pathname)?.id||'workspace';
 const [page,setPage]=useState<Page>(fromPath),[cases,setCases]=useState<RefillCase[]>(()=>connected?[]:loadDemo()),[selected,setSelected]=useState('RX-1042'),[role,setRole]=useState<Role>('staff'),[actor,setActor]=useState('Jordan Ellis'),[tenant,setTenant]=useState('Cedar Health'),[session,setSession]=useState(!connected),[loading,setLoading]=useState(connected),[loadError,setLoadError]=useState('');
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('All active'),[toast,setToast]=useState(''),[modal,setModal]=useState<'new'|'action'|'reset'|null>(null),[action,setAction]=useState<ActionType>('approve'),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[outage,setOutage]=useState(false),[detailTab,setDetailTab]=useState('Overview'),[error,setError]=useState('');
 const pendingId=useRef<string|null>(null);
 const [clockOffset,setClockOffset]=useState(0);
 const now=useNow(clockOffset);
 const refreshBusy=useRef(false),refreshEpoch=useRef(0);
 const current=cases.find(c=>c.id===selected)||cases[0];
 const active=cases.filter(c=>!isClosed(c));
 function notify(text:string){setToast(text);}
 async function refresh(silent=false){if(!connected||refreshBusy.current)return;refreshBusy.current=true;const epoch=refreshEpoch.current;if(!silent)setLoading(true);try{const data=await api();if(epoch!==refreshEpoch.current)return;setCases(previous=>data.cases.map((incoming:RefillCase)=>{const existing=previous.find(c=>c.id===incoming.id);return existing&&existing.version>incoming.version?existing:incoming;}));setRole(data.role);setActor(data.actor);setTenant(data.tenant);if(data.serverNow)setClockOffset(Date.parse(data.serverNow)-Date.now());setLoadError('');}catch(e){if(epoch===refreshEpoch.current)setLoadError((e as Error).message);}finally{refreshBusy.current=false;if(epoch===refreshEpoch.current)setLoading(false);}}
 useEffect(()=>{if(!connected||!session)return;const poll=()=>void refresh(true);const id=window.setInterval(poll,5000);window.addEventListener('focus',poll);return()=>{clearInterval(id);window.removeEventListener('focus',poll);};},[session]);
 useEffect(()=>{if(!supabase){setLoading(false);return;}const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,s)=>{setSession(!!s);if(s){setTimeout(()=>void refresh(),0);}else{refreshEpoch.current++;setCases([]);setLoading(false);}});return()=>subscription.unsubscribe();},[]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(id);},[toast]);
 useEffect(()=>{const back=()=>setPage(fromPath());window.addEventListener('popstate',back);const storage=(e:StorageEvent)=>{if(!connected&&e.key==='relayrx-synthetic-demo-v1')setCases(loadDemo());};window.addEventListener('storage',storage);return()=>{window.removeEventListener('popstate',back);window.removeEventListener('storage',storage);};},[]);
 useEffect(()=>{
  type MC={registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>};
  const context=(document as Document&{modelContext?:MC}).modelContext;if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  void Promise.resolve(context.registerTool({name:'inspect_refill_queue',description:'Read the visible synthetic refill queue, current blockers, owner roles, and signal strengths. Makes no changes.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');return cases.map(c=>({id:c.id,status:state(c),owner:c.owner,signal:signal(c),needsAttention:needsAttention(c),attentionExplanation:waitingExplanation(c),next:nextAction(c).label}));}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();
 },[cases]);
 function navigate(p:Page){setPage(p);history.pushState(null,'',`/${p}`);window.scrollTo(0,0);}
 function begin(type:ActionType){setAction(type);setNote('');setError('');pendingId.current=newId();setModal('action');}
 async function perform(e:FormEvent){e.preventDefault();if(!current)return;setBusy(true);setError('');try{const payload={type:action,note,requestId:pendingId.current!,expectedVersion:current.version,simulateFailure:outage};if(connected){const data=await api({operation:'act',caseId:current.id,action:payload});setCases(prev=>prev.map(c=>c.id===current.id?data.case:c));}else{setCases(demoAction(loadDemoWithCurrent(),current.id,payload,role));}setModal(null);notify(action==='patient_update'?'Patient update saved to the preview outbox.':'Workflow updated. Evidence added to the audit trail.');}catch(e){setError((e as Error).message);if(connected)void refresh();else setCases(loadDemo());}finally{setBusy(false);}}
 function loadDemoWithCurrent(){const saved=loadDemo();return saved.some(c=>c.id===current?.id)?saved:cases;}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const patient=String(f.get('patient')).trim(),medication=String(f.get('medication')).trim(),reason=String(f.get('reason'));if(patient.length<2||medication.length<2)throw new Error('Enter a sample patient alias and medication.');if(connected){const data=await api({operation:'create',patient,medication,reason,requestId:pendingId.current});await refresh();setSelected(data.case.id);}else{const updated=demoCreate(cases,patient,medication,reason);setCases(updated);setSelected(updated[0].id);}setModal(null);setFilter('All active');navigate('workspace');notify('Synthetic refill created and assigned.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const visible=cases.filter(c=>`${c.patient} ${c.id} ${c.medication} ${state(c)}`.toLowerCase().includes(query.toLowerCase())).filter(c=>filter==='All active'?!isClosed(c):filter==='Needs attention'?needsAttention(c,now):filter==='Ready to route'?state(c)==='Ready to route':filter==='My queue'?!isClosed(c)&&c.owner===role:isClosed(c));
 if(connected&&!session)return <Login/>;
 const RoleIcon=roleIcons[role];
 return <div className="app-shell"><a className="skip-link" href="#main">Skip to workspace</a>
  <aside className="sidebar"><a className="brand" href="/workspace" onClick={e=>{e.preventDefault();navigate('workspace');}}><span className="brand-mark">r</span><b>RelayRx<span>™</span></b></a><div className="practice"><span className="practice-avatar">CH</span><div><b>{tenant}</b><small>Care coordination</small></div><ChevronDown size={14}/></div><span className="nav-label">WORKSPACE</span><nav>{pages.slice(0,4).map(p=><button key={p.id} aria-label={p.label} title={p.label} onClick={()=>navigate(p.id)} className={page===p.id?'active':''}><p.icon size={19}/><span>{p.label}</span>{p.id==='workspace'&&<b>{active.length}</b>}{p.id==='lab'&&<i className="new-tag">NEW</i>}</button>)}<span className="nav-label">BUILD & GROW</span>{pages.slice(4).map(p=><button key={p.id} aria-label={p.label} title={p.label} onClick={()=>navigate(p.id)} className={page===p.id?'active':''}><p.icon size={19}/><span>{p.label}</span></button>)}</nav><div className="sidebar-bottom"><div className="circuit-tip"><GitBranch size={23}/><b>A clearer path to care.</b><p>One connected workflow.<br/>No refill left in the dark.</p><button onClick={()=>navigate('lab')}>Explore the circuit <ArrowUpRight size={15}/></button></div><div className="user"><span className="avatar small">JE</span><div><b>{connected?actor:'Jordan Ellis'}</b><small>{connected?'Sandbox member':'Demo workspace'}</small></div>{connected?<button aria-label="Sign out" className="icon-button" onClick={()=>void supabase?.auth.signOut()}><LogOut size={16}/></button>:<ShieldCheck size={18}/>}</div></div></aside>
  <div className="app-body"><header className="topbar"><span><span className="breadcrumb">Care operations</span><ChevronRight size={13}/><b>{pages.find(p=>p.id===page)?.label}</b></span><div className="topbar-right"><Badge tone="neutral"><FlaskConical size={12}/>{connected?'Connected sandbox':'Synthetic demo'}</Badge><div className="role-select"><RoleIcon size={16}/>{connected?<span>{roleNames[role]}</span>:<select value={role} onChange={e=>{setRole(e.target.value as Role);notify(`Demo role: ${roleNames[e.target.value as Role]}`);}} aria-label="Demo role"><option value="staff">Practice staff</option><option value="clinician">Clinician</option><option value="pharmacy">Pharmacy</option></select>}</div><button className="icon-button" onClick={()=>navigate('updates')} aria-label="View patient updates"><Bell size={18}/></button></div></header>
  <main id="main">
   {loadError&&<div className="error-box" role="alert">{loadError} <button onClick={()=>void refresh()}>Retry connection</button></div>}
   {page==='workspace'&&<><div className="page-heading"><div><div className="eyebrow">THE REFILL CONTROL ROOM</div><h1>Keep refills moving<span className="coral">.</span></h1><p>See the blocker. Find the owner. Close the loop.</p></div><div className="heading-actions">{connected&&<button className="button" onClick={()=>void refresh()}><RefreshCw size={16}/>Refresh</button>}<button className="button primary" disabled={role==='clinician'} title={role==='clinician'?'Intake is handled by practice staff or pharmacy':''} onClick={()=>{pendingId.current=newId();setError('');setModal('new');}}><Plus size={17}/>New refill</button></div></div>
   <div className="metrics"><Metric icon={GitBranch} label="Active refills" value={active.length} caption="Across the shared queue"/><Metric icon={Clock3} label="Needs attention" value={cases.filter(c=>needsAttention(c,now)).length} caption="Waiting 3 min · 30h simulated" tone="orange" onClick={()=>{setFilter('Needs attention');setQuery('');}}/><Metric icon={Zap} label="Ready to route" value={active.filter(c=>state(c)==='Ready to route').length} caption="All requirements verified" tone="green"/><Metric icon={CircleCheck} label="Loop closed" value={cases.filter(c=>c.transport==='dispensed').length} caption="Confirmed pharmacy pickup" tone="green"/></div>
   <div className="workspace-layout"><section className="queue panel"><div className="queue-heading"><h2>Refill queue <span>{visible.length}</span></h2><SlidersHorizontal size={17}/></div><label className="search"><Search size={16}/><input placeholder="Search patient, medication, ID…" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search refill queue"/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search"><X size={14}/></button>}</label><div className="queue-filter"><select aria-label="Filter refill queue" value={filter} onChange={e=>setFilter(e.target.value)}>{['All active','Needs attention','Ready to route','My queue','Closed'].map(s=><option key={s}>{s}</option>)}</select><span>Oldest first</span></div><div className="case-list">{loading?<div className="empty"><RefreshCw size={22}/>Loading your queue…</div>:visible.length===0?<div className="empty"><CheckCircle2 size={26}/><b>No refills here</b><p>Try a different filter or start a sample refill.</p></div>:[...visible].sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).map(c=><button key={c.id} className={`case-row ${current?.id===c.id?'selected':''}`} onClick={()=>{setSelected(c.id);setDetailTab('Overview');}}><div className="case-top"><span className={`avatar avatar-${c.initials.charCodeAt(0)%4}`}>{c.initials}</span><div><b>{c.patient}</b><span>{c.medication} <i>·</i> {c.id}</span></div><ChevronRight size={15}/></div><div className="case-status"><Badge tone={statusTone(c)}>{state(c)}</Badge><WaitingTimer c={c} now={now} compact/></div><div className="case-bottom"><span>{roleNames[c.owner]}</span><Signal value={signal(c)} small/></div></button>)}</div><div className="queue-footer"><ShieldCheck size={14}/>Synthetic records · no patient data</div></section>
   {current?<section className="detail panel"><div className="detail-head"><div><div className="detail-id">{current.id}<span>•</span>EXISTING PRESCRIPTION</div><h2>{current.patient}</h2><p>{current.medication}<span>·</span>{current.pharmacy}</p></div><Badge tone={statusTone(current)}>{state(current)}</Badge></div><div className="detail-tabs" role="tablist">{['Overview','Activity','Patient update'].map(t=><button role="tab" aria-selected={detailTab===t} className={detailTab===t?'active':''} key={t} onClick={()=>setDetailTab(t)}>{t}{t==='Activity'&&<span>{current.events.length}</span>}</button>)}</div>
   <div className="detail-wait"><WaitingTimer c={current} now={now}/></div>{detailTab==='Overview'?<div className="detail-content"><div className="blocker-note"><div className="blocker-icon"><Info size={17}/></div><div><b>{current.reason}</b><p>{nextAction(current).why}</p></div></div><Circuit c={current} onInput={(key:InputKey)=>{const i=INPUTS.find(i=>i.key===key)!;if(current.inputs[key].verified){notify(`${i.name}: ${current.inputs[key].note}`);}else if(permitted(i.action,role)){begin(i.action);}else notify(`Switch to ${roleNames[i.role]} to record this verification.`);}}/>
    <div className="next-action"><div className="next-label"><span><span className="pulse-dot"/>NEXT BEST ACTION</span><Badge>{roleNames[nextAction(current).role]}</Badge></div><h3>{nextAction(current).label}</h3><p>{nextAction(current).why}</p>{nextAction(current).type&&<button className="button primary" disabled={!permitted(nextAction(current).type!,role)||busy} onClick={()=>begin(nextAction(current).type!)}>{nextAction(current).label}<ArrowRight size={16}/></button>}{nextAction(current).type&&!permitted(nextAction(current).type!,role)&&<small className="role-hint"><LockKeyhole size={13}/>{connected?`Requires ${roleNames[nextAction(current).role]} authorization.`:`Use the role selector above to continue as ${roleNames[nextAction(current).role].toLowerCase()}.`}</small>}</div>
    <div className="requirements"><div className="section-heading"><h3>What powers this refill</h3><span>{INPUTS.filter(i=>current.inputs[i.key].verified).length} / 5 verified</span></div>{INPUTS.map(i=><div className="requirement" key={i.key}><span className={`check-circle ${current.inputs[i.key].verified?'checked':''}`}>{current.inputs[i.key].verified?<Check size={12}/>:<span/>}</span><div><b>{i.name}</b><small>{current.inputs[i.key].verified?`Verified by ${current.inputs[i.key].by}`:current.inputs[i.key].note}</small></div>{current.inputs[i.key].verified?<span className="verified-text">+3</span>:<button className="text-button" onClick={()=>begin(i.action)} disabled={!permitted(i.action,role)||current.hold}>{i.label}<ArrowUpRight size={13}/></button>}</div>)}</div>
    <div className="detail-footer"><button className="text-button" onClick={()=>begin('patient_update')}><MessageSquare size={15}/>Prepare patient update</button>{!isClosed(current)&&<div className="secondary-actions">{role==='clinician'&&!current.hold&&<button className="text-button danger" onClick={()=>begin('hold')}>Place hold</button>}{role==='clinician'&&!current.hold&&current.transport==='not_sent'&&<button className="text-button danger" onClick={()=>begin('decline')}>Decline</button>}{current.transport==='not_sent'&&!current.hold&&<button className="text-button" onClick={()=>begin('invalidate')}>Flag mismatch</button>}{role==='pharmacy'&&current.transport==='failed'&&!current.hold&&<button className="text-button" onClick={()=>begin('acknowledge')}>Record manual confirmation</button>}</div>}</div></div>:detailTab==='Activity'?<div className="detail-content"><div className="section-heading"><h3>Evidence & handoffs</h3><Badge>Version {current.version}</Badge></div><p className="muted">Every workflow change records its actor, evidence, and resulting signal.</p><Audit c={current}/></div>:<div className="detail-content"><PatientPreview c={current}/><button className="button primary" onClick={()=>begin('patient_update')}><MessageSquare size={16}/>Save update preview</button><p className="fine-print">Messages stay in this sandbox. No SMS or email is sent.</p></div>}</section>:<section className="panel empty"><GitBranch size={36}/><h2>Your queue is ready</h2><p>Create a synthetic refill to begin the workflow.</p></section>}</div>
   <div className="workspace-note"><LockKeyhole size={14}/><span>The signal represents verified workflow evidence. Clinical prescribing decisions always belong to authorized professionals.</span><button className="text-button" onClick={()=>navigate('lab')}>How it works<ArrowUpRight size={14}/></button></div></>}
   {page==='lab'&&<Lab/>}
   {page==='updates'&&<><PageHeading eyebrow="CLOSE THE COMMUNICATION GAP" title="Keep the patient in the loop." description="Clear next steps, based on verified workflow state."/><div className="inline-notice"><Info size={17}/>Preview outbox only. No messages are delivered to patients.</div><div className="updates-grid">{cases.map(c=><section className="panel update-card" key={c.id}><div className="section-heading"><div><h3>{c.patient}</h3><span className="muted">{c.id}</span></div><Badge tone={statusTone(c)}>{state(c)}</Badge></div><p>{patientText(c)}</p><div className="update-card-footer"><span>{c.updates.length} saved preview{c.updates.length!==1?'s':''}</span><button className="text-button" onClick={()=>{setSelected(c.id);setDetailTab('Patient update');navigate('workspace');}}>Review update<ArrowRight size={14}/></button></div>{c.updates[0]&&<details><summary>Last saved preview · {humanTime(c.updates[0].at)}</summary><p>{c.updates[0].text}</p></details>}</section>)}</div></>}
   {page==='insights'&&<Insights cases={cases} now={now}/>}
   {page==='growth'&&<Growth/>}
   {page==='system'&&<System outage={outage} setOutage={setOutage} connected={connected} onReset={()=>setModal('reset')}/>}
  </main><footer className="app-footer"><span>RelayRx <span>·</span> Connected care, one handoff at a time.</span><span>Hackathon prototype <span>·</span> v1.1</span></footer></div>
  <Copilot c={current} role={role} now={now} onRoleChange={connected?undefined:setRole} onRefresh={()=>{if(connected)void refresh(true);else setCases(loadDemo());}}/>
  {toast&&<div className="toast" role="status"><CheckCircle2 size={18}/><span>{toast}</span><button onClick={()=>setToast('')} aria-label="Dismiss notification"><X size={15}/></button></div>}
  {modal==='new'&&<Modal title="Start a sample refill" onClose={()=>!busy&&setModal(null)}><p className="muted">Use a fictional patient alias. This workspace is for synthetic data only.</p><form onSubmit={create}><label>Sample patient alias<input autoFocus required name="patient" placeholder="e.g. Taylor Reed" maxLength={70}/></label><label>Existing medication<input required name="medication" placeholder="e.g. Lisinopril" maxLength={80}/></label><label>Why is the refill stuck?<select name="reason">{SCENARIOS.map(s=><option key={s}>{s}</option>)}</select></label><div className="inline-notice small-notice"><Info size={16}/>This creates a simulated intake with sample evidence. No prescription is written.</div>{error&&<div role="alert" className="error-box">{error}</div>}<div className="modal-actions"><button className="button" type="button" onClick={()=>setModal(null)} disabled={busy}>Cancel</button><button className="button primary" disabled={busy}>{busy?'Creating…':'Create sample refill'}<Plus size={16}/></button></div></form></Modal>}
  {modal==='action'&&current&&<Modal title={actionTitle(action)} onClose={()=>!busy&&setModal(null)}><div className="action-context"><b>{current.patient}</b><span>{current.id} · {roleNames[role]}</span></div><p className="muted">{actionDescription(action)}</p>{action==='patient_update'&&<div className="message-bubble">{patientText(current)}</div>}{action==='dispatch'&&<div className="inline-notice"><Info size={17}/>Simulated handoff. No e-prescription is transmitted.</div>}{(action==='hold'||action==='decline')&&current.transport!=='not_sent'&&<p className="error-box">A handoff already exists. This hold blocks local progress but cannot recall an external prescription. Contact the pharmacy immediately.</p>}<form onSubmit={perform}><label>{action==='approve'?'Clinician decision evidence':'Evidence / reason'}<textarea required minLength={8} maxLength={1500} autoFocus value={note} onChange={e=>setNote(e.target.value)} placeholder={action==='approve'?'Record the authorized clinician’s review and decision for this exact request…':'Describe what was verified, the source, and the next step…'} rows={4}/></label><p className="fine-print">Synthetic notes only. Minimum 8 characters. Saved with your role and a timestamp.</p>{error&&<div className="error-box" role="alert">{error}</div>}<div className="modal-actions"><button className="button" type="button" onClick={()=>setModal(null)} disabled={busy}>Cancel</button><button className="button primary" disabled={busy||!permitted(action,role)}>{busy?'Saving…':action==='approve'?'Record clinician approval':'Confirm & record'}<Check size={16}/></button></div></form></Modal>}
  {modal==='reset'&&<Modal title="Reset the synthetic demo?" onClose={()=>setModal(null)}><p>This replaces the sample cases and their local audit history with the original six records.</p><div className="modal-actions"><button className="button" onClick={()=>setModal(null)}>Cancel</button><button className="button primary" onClick={()=>{try{const fresh=seedCases();saveDemo(fresh);setCases(fresh);setSelected(fresh[0].id);setOutage(false);setModal(null);notify('The sample workspace has been reset.');}catch{notify('Browser storage is unavailable. The reset was not saved.');}}}>Reset demo</button></div></Modal>}
 </div>;
}
function Metric({icon:Icon,label,value,caption,tone='neutral',onClick}:{icon:LucideIcon;label:string;value:number|string;caption:string;tone?:string;onClick?:()=>void}){const content=<><div><span>{label}</span><Icon size={17}/></div><strong>{String(value).padStart(2,'0')}</strong><small>{caption}</small></>;return onClick?<button className={`metric metric-button ${tone}`} onClick={onClick} aria-label={`Needs attention: ${value}. Show waiting cases`}>{content}</button>:<div className={`metric ${tone}`}>{content}</div>;}
export function PageHeading({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div></div>;}
function PatientPreview({c}:{c:RefillCase}){return <div className="patient-preview"><div className="section-heading"><h3>Patient status preview</h3><Badge>Not sent</Badge></div><div className="message-bubble"><span className="message-from"><span className="mini-logo">r</span> Your care team</span><p>{patientText(c)}</p><small>Updated from verified workflow status</small></div><div className="patient-steps">{['Request received','Care team review','Pharmacy confirmation','Medication received'].map((s,i)=><div key={s} className={(i===0||(i===1&&c.inputs.approval.verified)||(i===2&&['acknowledged','dispensed'].includes(c.transport))||(i===3&&c.transport==='dispensed'))?'done':''}><CheckCircle2 size={17}/>{s}</div>)}</div></div>;}
function Audit({c}:{c:RefillCase}){return <ol className="audit-list">{c.events.map(e=><li key={e.id}><span className="audit-marker"><Activity size={13}/></span><div><div className="audit-heading"><b>{e.type.replaceAll('_',' ')}</b><span>{humanTime(e.at)}</span></div><p>{e.note}</p><small>{e.actor} · Signal {e.signal}/15 · {e.role}</small></div></li>)}</ol>;}
function actionTitle(type:ActionType){return ({verify_identity:'Verify patient identity',verify_prescription:'Verify prescription details',clear_visit:'Record visit / review decision',confirm_coverage:'Confirm administrative resolution',approve:'Record clinician authorization',hold:'Place a clinical hold',release_hold:'Resolve the clinical hold',decline:'Record a declined refill',dispatch:'Route the pharmacy handoff',retry:'Retry the handoff',acknowledge:'Confirm pharmacy readiness',dispense:'Confirm medication pickup',request_info:'Request missing information',patient_update:'Prepare a patient update',invalidate:'Flag an identity mismatch',escalate:'Escalate for manual follow-up'})[type];}
function actionDescription(type:ActionType){return ({approve:'Record an existing clinical decision made by an authorized professional. The readiness score never makes this decision.',clear_visit:'A clinician must determine whether a visit is required and record that the requirement is satisfied or not applicable.',hold:'A hold immediately locks the circuit and invalidates the prior approval. If a pharmacy handoff exists, contact the pharmacy directly.',release_hold:'Document how the concern was resolved. A fresh clinician approval will still be required.',decline:'Record the clinician’s decision and the appropriate follow-up. This closes the workflow without a refill.',dispatch:'All five inputs must be verified. A queued handoff remains open until pharmacy readiness and pickup are confirmed.',retry:'Retry the same logical handoff. After three failed attempts, the workflow requires manual follow-up.',acknowledge:'Record pharmacy evidence of receipt, preparation, and final checks. This is separate from sending the handoff.',dispense:'Record pharmacy confirmation that medication was dispensed to the patient or delivered. This closes the loop.',patient_update:'Review the state-based wording below. The message is saved to a preview outbox and is not sent.',invalidate:'An identity mismatch removes identity verification and invalidates any prior clinician approval.',escalate:'Record an owner and follow-up plan. Contact the pharmacy and verify the actual outcome; escalation alone does not resolve the refill.',verify_identity:'Match the patient identifiers using the appropriate source and record the evidence.',verify_prescription:'Reconcile the existing prescription with an authoritative source. This does not authorize a new prescription.',confirm_coverage:'Record the confirmed insurance or administrative resolution. The application does not determine coverage.',request_info:'Record exactly what is missing and who will obtain it.'})[type];}
function Lab(){
 const [rear,setRear]=useState(9),[side,setSide]=useState(12),[mode,setMode]=useState<'compare'|'subtract'>('compare'),[hold,setHold]=useState(false),[checks,setChecks]=useState([true,true,true,false,false]);
 const raw=comparator(rear,side,mode), evidence=checks.filter(Boolean).length*3, ready=comparator(evidence,15)>0&&!hold;
 return <><PageHeading eyebrow="A LITTLE REDSTONE. A LOT OF CLARITY." title="Build a circuit. Understand the flow." description="Explore the Minecraft-inspired logic behind a refill handoff."/><div className="lab-layout"><section className="panel lab-card"><div className="section-heading"><h2>The comparator</h2><Badge tone="coral">Interactive</Badge></div><p>A rear input is compared with a side input. Change the values and watch the output.</p><div className="segmented" role="group" aria-label="Comparator mode"><button className={mode==='compare'?'active':''} onClick={()=>setMode('compare')}>Compare mode</button><button className={mode==='subtract'?'active':''} onClick={()=>setMode('subtract')}>Subtract mode</button></div><div className="lab-diagram"><div><span>REAR INPUT</span><b>{rear}</b></div><div className="lab-wire"/><div className="lab-comparator">{mode==='compare'?'≥':'−'}</div><div className={`lab-wire ${raw?'lit':''}`}/><div className={raw?'lab-output lit':'lab-output'}><span>OUTPUT</span><b>{raw}</b></div></div><label className="range-label">Rear signal <b>{rear}/15</b><input type="range" min="0" max="15" value={rear} onChange={e=>setRear(+e.target.value)}/></label><label className="range-label">Side signal <b>{side}/15</b><input type="range" min="0" max="15" value={side} onChange={e=>setSide(+e.target.value)}/></label><div className="formula">{mode==='compare'?`A ≥ B ? A : 0  →  ${rear} ≥ ${side}  →  ${raw}`:`max(A − B, 0)  →  max(${rear} − ${side}, 0)  →  ${raw}`}</div><p className="fine-print">Comparison passes equal signals too. Subtraction removes the larger side input from the rear input, with a floor of zero.</p></section>
 <section className="panel lab-card"><div className="section-heading"><h2>The refill circuit</h2><Badge>{ready?'Circuit complete':'Complete the circuit'}</Badge></div><p>Connect five pieces of verified evidence. Each contributes 3 signal units. Every input is mandatory.</p><div className="lab-checks">{INPUTS.map((i,n)=><label key={i.key}><input type="checkbox" checked={checks[n]} onChange={e=>setChecks(prev=>prev.map((v,k)=>k===n?e.target.checked:v))}/><span>{i.name}</span><b className={checks[n]?'green':''}>+{checks[n]?3:0}</b></label>)}</div><div className="lab-result"><div><span>Workflow readiness</span><Signal value={evidence}/></div><Badge tone={ready?'green':'amber'}>{hold?'HOLD OVERRIDE':ready?'HANDOFF UNLOCKED':'HANDOFF LOCKED'}</Badge></div><label className="hold-switch"><input type="checkbox" checked={hold} onChange={e=>setHold(e.target.checked)}/><span>Activate clinician hold</span><LockKeyhole size={16}/></label><p className="fine-print">Try 15/15 with a hold active: the handoff stays locked. This lab never changes patient cases.</p></section></div>
 <div className="concept-grid">{[{icon:Zap,title:'Signal strength → readiness',text:'0–15 shows how much required evidence is verified. It is not a probability, urgency score, or clinical recommendation.'},{icon:GitBranch,title:'Comparator → requirement gate',text:'The fixed threshold is 15. A separate all-input check and clinician hold prevent a partial score from bypassing a requirement.'},{icon:RefreshCw,title:'Repeater → bounded retry',text:'A failed handoff can be retried up to three total attempts. Retries preserve the same case and require outcome confirmation.'},{icon:Clock3,title:'Signal loss → attention cue',text:'In Minecraft, dust loses strength over distance. Here, 3 minutes waiting on the current action means 30 simulated hours and flags Needs Attention. Verified evidence never decays and the workflow does not advance on a timer.'}].map(x=><section className="panel concept" key={x.title}><x.icon size={23}/><h3>{x.title}</h3><p>{x.text}</p></section>)}</div><div className="inline-notice"><ShieldCheck size={18}/>The game element teaches workflow mechanics. There are no rewards for prescribing, approving faster, or bypassing review.</div><p className="fine-print">Inspired by redstone logic; this is not a Minecraft product. <a href="https://www.minecraft.net/en-us/article/taking-inventory--redstone-comparator" target="_blank" rel="noreferrer">Read the comparator guide <ExternalLink size={11}/></a></p></>;
}
